// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// dann_set_threads_C
int dann_set_threads_C(int n);
RcppExport SEXP _dann_dann_set_threads_C(SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(dann_set_threads_C(n));
    return rcpp_result_gen;
END_RCPP
}
// dann_get_threads_C
int dann_get_threads_C();
RcppExport SEXP _dann_dann_get_threads_C() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(dann_get_threads_C());
    return rcpp_result_gen;
END_RCPP
}
// dann_max_threads_C
int dann_max_threads_C();
RcppExport SEXP _dann_dann_max_threads_C() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(dann_max_threads_C());
    return rcpp_result_gen;
END_RCPP
}
// dann_has_openmp_C
bool dann_has_openmp_C();
RcppExport SEXP _dann_dann_has_openmp_C() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(dann_has_openmp_C());
    return rcpp_result_gen;
END_RCPP
}
// dann_predict_all_C
Rcpp::List dann_predict_all_C(const arma::mat& xTrain, const arma::vec& yTrain, const arma::mat& xTest, int k, int neighborhood_size, double epsilon, const arma::vec& y_class_precedence, const arma::vec& unique_classes, bool probability);
RcppExport SEXP _dann_dann_predict_all_C(SEXP xTrainSEXP, SEXP yTrainSEXP, SEXP xTestSEXP, SEXP kSEXP, SEXP neighborhood_sizeSEXP, SEXP epsilonSEXP, SEXP y_class_precedenceSEXP, SEXP unique_classesSEXP, SEXP probabilitySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type xTrain(xTrainSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type yTrain(yTrainSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type xTest(xTestSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type neighborhood_size(neighborhood_sizeSEXP);
    Rcpp::traits::input_parameter< double >::type epsilon(epsilonSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y_class_precedence(y_class_precedenceSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type unique_classes(unique_classesSEXP);
    Rcpp::traits::input_parameter< bool >::type probability(probabilitySEXP);
    rcpp_result_gen = Rcpp::wrap(dann_predict_all_C(xTrain, yTrain, xTest, k, neighborhood_size, epsilon, y_class_precedence, unique_classes, probability));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_dann_dann_set_threads_C", (DL_FUNC) &_dann_dann_set_threads_C, 1},
    {"_dann_dann_get_threads_C", (DL_FUNC) &_dann_dann_get_threads_C, 0},
    {"_dann_dann_max_threads_C", (DL_FUNC) &_dann_dann_max_threads_C, 0},
    {"_dann_dann_has_openmp_C", (DL_FUNC) &_dann_dann_has_openmp_C, 0},
    {"_dann_dann_predict_all_C", (DL_FUNC) &_dann_dann_predict_all_C, 9},
    {NULL, NULL, 0}
};

RcppExport void R_init_dann(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
