# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @keywords internal
#' Function to calculate distance between all training data points and one test point.
calc_distance_C <- function(trainX, testX) {
    .Call(`_dann_calc_distance_C`, trainX, testX)
}

